server:
  port: 9001
spring:
  application:
    name: lym-config-client
  rabbitmq: 
    host: 127.0.0.1
    port: 5672
    username: liyiming
    password: 123456

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  security:
    enabled: false