server:
#服务的端口
  port: 9003
spring:
  application:
#服务的名称
    name: lym-serviceB

eureka:
  instance:
    prefer-ip-address: true
#Eureka注册服务列表显示ip+端口
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/