server:
#服务的端口
  port: 8771
spring:
  application:
#服务的名称
    name: lym-zuul-service

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: lym-serviceA
    api-b:
      path: /api-b/**
      serviceId: lym-serviceB