server:
  port: 8781
spring:
  application:
    name: lym-ha-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lym84180790/Spring-Cloud-Learning.git
          searchPaths: configRepo
          username: 
          password: 
      label: master

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/