server:
  port: 8781
spring:
  application:
    name: lym-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lym84180790/Spring-Cloud-Learning.git
          searchPaths: configRepo
          username: 
          password: 
      label: master
